version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: peturgeorgievv-nestjs-starter-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - my_postgres_data:/var/lib/postgresql/data # Persist data even when container shuts down
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - redis-network

volumes:
  my_postgres_data:
  redis:
  redis-config:

networks:
  redis-network:
    driver: bridge